# Generated by Django 3.2.14 on 2022-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='preferred_loc',
            field=models.CharField(choices=[('ON', 'Online'), ('PU', 'Public/Cafe'), ('PI', 'Private/Home'), ('OT', 'Unknown')], default='PI', max_length=255, verbose_name='preferred_loc'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='Please add first name', max_length=255, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='Please add last name', max_length=255, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='TestUser', max_length=100, unique=True, verbose_name='username'),
        ),
    ]
