# Generated by Django 3.2.14 on 2022-09-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0007_auto_20220920_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='payment',
            new_name='pay',
        ),
    ]
