# Generated by Django 4.1.1 on 2022-10-10 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0009_myuser_is_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayException', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DayMonthException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthException', models.TextField()),
                ('DayException', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthException', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Opening', models.TimeField()),
                ('Closing', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('author_profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author_profile_link', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Opening', models.TimeField()),
                ('Closing', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pay',
            field=models.CharField(choices=[('c', 'Cash'), ('paypal', 'Paypal'), ('card', 'Card'), ('rev', 'Revolut'), ('NA', 'Not Available')], default='c', max_length=255, verbose_name='pay'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='preferred_loc',
            field=models.CharField(choices=[('ON', 'Online'), ('PU', 'Public/Cafe'), ('PI', 'Private/Home'), ('OT', 'Unknown'), ('NA', 'Not Available')], default='PI', max_length=255, verbose_name='preferred_loc'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='year',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('six_p', '6+'), ('OT', 'Other'), ('NA', 'Not Available')], default='one', max_length=255, verbose_name='year'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(blank=True)),
                ('for_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('Duration', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
