# Generated by Django 4.1.1 on 2022-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0010_dayexception_daymonthexception_monthexception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='author_school_and_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
