# Generated by Django 4.1.1 on 2022-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0011_testimonial_author_school_and_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('associated_with', models.CharField(max_length=255, null=True)),
                ('association_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
