# Generated by Django 4.1.1 on 2022-10-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0012_teaching_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching_experience',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_experience',
            name='associated_with',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_experience',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
