# Generated by Django 4.1.1 on 2022-11-21 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0016_photosection_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dateTime', models.DateTimeField()),
                ('end_dateTime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('start_dateTime', 'end_dateTime')},
            },
        ),
        migrations.DeleteModel(
            name='DayException',
        ),
        migrations.DeleteModel(
            name='DayMonthException',
        ),
        migrations.DeleteModel(
            name='MonthException',
        ),
        migrations.DeleteModel(
            name='TimeException',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='sent_date',
            new_name='issued_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='for_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='request',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 16, 33, 5, 466722)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(choices=[('NS', 'Not Specified'), ('ON', 'Online'), ('PU', 'Public/Cafe'), ('PI', 'Private/Home'), ('OT', 'Other'), ('NA', 'Not Available')], default='NS', max_length=255, verbose_name='preferred_loc'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('c', 'Cash'), ('paypal', 'Paypal'), ('card', 'Card'), ('rev', 'Revolut'), ('NA', 'Not Available')], default='c', max_length=255, verbose_name='pay'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 16, 33, 5, 466706), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='preferred_loc',
            field=models.CharField(choices=[('NS', 'Not Specified'), ('ON', 'Online'), ('PU', 'Public/Cafe'), ('PI', 'Private/Home'), ('OT', 'Other'), ('NA', 'Not Available')], default='NS', max_length=255, verbose_name='preferred_loc'),
        ),
    ]
