# Generated by Django 4.1.3 on 2022-11-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0016_photosection_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
