# Generated by Django 4.1.1 on 2022-11-21 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0017_remove_myuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offs',
            fields=[
                ('start_dateTime', models.DateTimeField(primary_key=True, serialize=False)),
                ('end_dateTime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='DayException',
        ),
        migrations.DeleteModel(
            name='DayMonthException',
        ),
        migrations.DeleteModel(
            name='MonthException',
        ),
        migrations.DeleteModel(
            name='TimeException',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='request',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='sent_date',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='for_date',
            new_name='start_dateTime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='accepted_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(choices=[('NS', 'Not Specified'), ('ON', 'Online'), ('PU', 'Public/Cafe'), ('PI', 'Private/Home'), ('OT', 'Other'), ('NA', 'Not Available')], default='NS', max_length=255, verbose_name='preferred_loc'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='TestUser', max_length=100, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='preferred_loc',
            field=models.CharField(choices=[('NS', 'Not Specified'), ('ON', 'Online'), ('PU', 'Public/Cafe'), ('PI', 'Private/Home'), ('OT', 'Other'), ('NA', 'Not Available')], default='NS', max_length=255, verbose_name='preferred_loc'),
        ),
    ]
