# Generated by Django 4.1.1 on 2022-11-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0017_offs_delete_dayexception_delete_daymonthexception_and_more'),
        ('BookingSystem', '0017_remove_myuser_username'),
    ]

    operations = [
    ]
