# Generated by Django 4.1.1 on 2022-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0018_offs_delete_dayexception_delete_daymonthexception_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_dateTime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
