# Generated by Django 4.1.1 on 2022-11-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0019_remove_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_dateTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
