# Generated by Django 4.1.1 on 2022-11-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0021_learningmaterial_remove_testimonial_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='Name',
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='type',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='upload',
            field=models.FileField(default='Not Found', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FilesLearningMaterial',
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
