# Generated by Django 4.1.1 on 2022-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0022_remove_learningmaterial_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
