# Generated by Django 4.1.3 on 2022-11-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0023_alter_learningmaterial_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
