# Generated by Django 4.1.3 on 2022-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0025_resettokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profilePic',
            field=models.ImageField(default='uploads/DefaultProfilePic.png', upload_to='uploads/'),
        ),
    ]
