# Generated by Django 4.1.3 on 2022-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingSystem', '0026_alter_myuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profilePic',
            field=models.ImageField(default='images/ProfilePics/DefaultProfilePic.png', upload_to='images/ProfilePics/'),
        ),
    ]
